name: Publish

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches:
      - 'main'
  release:
    types: [released]
  pull_request:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish:
    name: Build and publish container
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        php: ["8.2", "8.3", "8.4"]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ matrix.php == '8.4' && github.event_name == 'release' }}

            type=semver,pattern=v{{version}},enable=${{ matrix.php == '8.4' }}
            type=semver,pattern=v{{major}}.{{minor}},enable=${{ matrix.php == '8.4' }}
            type=semver,pattern=v{{major}},enable=${{ matrix.php == '8.4' }}
            type=edge,branch=main,enable=${{ matrix.php == '8.4' }}

            type=raw,value=php${{ matrix.php }},enable=${{ github.event_name == 'release' }}

            type=semver,pattern=v{{version}},suffix=-php${{ matrix.php }}
            type=semver,pattern=v{{major}}.{{minor}},suffix=-php${{ matrix.php }}
            type=semver,pattern=v{{major}},suffix=-php${{ matrix.php }}
            type=edge,branch=main,suffix=-php${{ matrix.php }}
            type=ref,event=pr,suffix=-php${{ matrix.php }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=${{ matrix.php }}
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64